# Only include theme settings for cloud deployment
# Do NOT include server settings like port or address
[theme]
base = "light"
primaryColor = "#D4AF37"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#1A2A44"